# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BGR <- function(X, burnIn, iterations, alpha = 1, mu = 0, verbose = TRUE) {
    .Call(`_baygel_BGR`, X, burnIn, iterations, alpha, mu, verbose)
}

